id: P010482
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG5478
  title: མངོན་རྟོགས་རྒྱན་གྱི་འགྲེལ་པ་འཇིག་རྟེན་གསུམ་སྒྲོན་
  author: ''
  volumes:
    1ddb2f4fd901419abe799678fac4d817:
      image_group_id: I1KG5485
      title: ''
      volume_number: 1
      total_pages: 292
      base_file: v001.txt
