id: I1CE433EF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T06:00:37+00:00'
last_modified: '2022-06-08T13:55:40.754340+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5478
  title: མངོན་རྟོགས་རྒྱན་གྱི་འགྲེལ་པ་འཇིག་རྟེན་གསུམ་སྒྲོན་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B54B:
      image_group_id: I1KG5485
      title: ''
      total_pages: 292
      order: 1
      base_file: B54B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
